# Based on https://gist.github.com/tzapu/abe4505f14b0c888c8e3b66e598f8bef
version: '1.0'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=America/New York
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=1000
      - PLEX_GID=1000
    hostname: smallcatlabs-dev
    volumes:
      - ./config:/config
      - ./transcode:/transcode
      - ${DATADIR}:/data
  transmission:
    container_name: transmission
    image: dperson/transmission
    restart: unless-stopped
    depends_on:
      - plex
    network_mode: host
    environment:
      - TZ=America/New York
      - TR_IDLE_SEEDING_LIMIT_ENABLED=true
      - TR_IDLE_SEEDING_LIMIT=600
      - TR_RATIO_LIMIT_ENABLED=true
      - TR_RATIO_LIMIT=4
      - TR_DOWNLOAD_DIR=/downloads
      - TR_INCOMPLETE_DIR_ENABLED=false
      - TR_RENAME_PARTIAL_FILES=true
      - TR_DHT_ENABLED=false
      - TR_PEX_ENABLED=false
      - USERID=1000
      - GROUPID=1000
    volumes:
      - ./config/transmission:/var/lib/transmission-daemon/info
      #set transmission or sonarr download folder to /downloads
      - ./downloads/complete:/downloads
      - ./downloads/temp:/var/lib/transmission-daemon/incomplete
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    restart: unless-stopped
    depends_on:
      - transmission
      - plex
    network_mode: host
    environment:
      - TZ=America/New York
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config/sonarr:/config
      - ${DATADIR}/video/tv:/tv
      - ./downloads/complete:/downloads
